
#define GUI_TILE_VALUE_MODIFIER 250.0

#define GUI_MAP_NUMERICALLY_REPRESENTABLE_VALUES ( 10 /* 0 - 9 */)
#define GUI_MAP_PROPERLY_REPRESENTABLE_VALUES ( 10 /*0:9*/ + 26 /*A-Z*/ )

#define GUI_HUD_COUNTRIES_PER_ROW 4
